{% set name = "urllib3-secure-extra" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/urllib3-secure-extra-{{ version }}.tar.gz
  sha256: ee9409cbfeb4b8609047be4c32fb4317870c602767e53fd8a41005ebe6a41dff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core >=3.2,<4
  run:
    - python >={{ python_min }}

test:
  imports:
    - urllib3_secure_extra
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/urllib3-secure-extra/
  summary: Marker library to detect whether urllib3 was installed with the deprecated [secure] extra
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
